# Generated by Django 5.2.1 on 2025-05-14 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Fluxx", "0002_post_likes_profile_delete_follow"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comment",
            new_name="text",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
