# Generated by Django 5.2.1 on 2025-05-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Fluxx", "0003_rename_comment_comment_text_delete_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="testing title", max_length=46),
        ),
    ]
