# Generated by Django 5.2.1 on 2025-05-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Fluxx", "0004_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.CharField(max_length=60),
        ),
    ]
