# Generated by Django 5.2.1 on 2025-05-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Fluxx", "0005_alter_comment_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(default="default.png", upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.CharField(default="bio", max_length=150),
            preserve_default=False,
        ),
    ]
